name: GitHub Security Alerts for Jira

on: workflow_dispatch

jobs:
  syncSecurityAlerts:
    runs-on: ubuntu-latest
    steps:
      - name: "Sync security alerts to Jira issues"
        uses: reload/github-security-jira@v1.x
        env:
          GH_SECURITY_TOKEN: ${{ secrets.GITHUBPT }}
          JIRA_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          JIRA_HOST: https://keerthanatest.atlassian.net
          JIRA_USER: keerthanagvsl64@gmail.com
          JIRA_PROJECT: TES
          JIRA_EPIC_LINK: TES-6
        
