name: GitHub Security Alerts for Jira

on: workflow_dispatch

jobs:
  syncSecurityAlerts:
    runs-on: ubuntu-latest
    steps:
     - name: print
       env:
          GH_SECURITY_TOKEN: ${{ secrets.GITHUBPT }}
          JIRA_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          JIRA_HOST: https://jira.sixt.com
          JIRA_USER: ${{ secrets.USER }}
       run:
          echo "$GH_SECURITY_TOKEN"
          echo "$JIRA_TOKEN"
          echo "$JIRA_USER"
       shell: bash
